// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace webtuyensinh.Migrations
{
    [DbContext(typeof(WebtuyensinhDbContext))]
    [Migration("20230720121156_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webtuyensinh.Models.AdmissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfTraining")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Admission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2670),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A1",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Đà Nẵng",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2675),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A2",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2680),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A3",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 4,
                            Address = "HCM",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2685),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A4",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "HCM",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2849),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A5",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 6,
                            Address = "HCM",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2854),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A6",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2859),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A7",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 8,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2865),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A8",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 9,
                            Address = "Đà Nẵng",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2871),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A9",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        },
                        new
                        {
                            Id = 10,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2877),
                            Desire = "......",
                            EducationLevel = 5,
                            Name = "Nguyễn Văn A10",
                            PhoneNumber = "0369109466",
                            TypeOfTraining = 0
                        });
                });

            modelBuilder.Entity("webtuyensinh.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2950),
                            Description = "......",
                            Name = "Danh mục tin tức 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2955),
                            Description = "......",
                            Name = "Danh mục tin tức 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2959),
                            Description = "......",
                            Name = "Danh mục tin tức 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2963),
                            Description = "......",
                            Name = "Danh mục tin tức 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2966),
                            Description = "......",
                            Name = "Danh mục tin tức 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2970),
                            Description = "......",
                            Name = "Danh mục tin tức 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2974),
                            Description = "......",
                            Name = "Danh mục tin tức 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2978),
                            Description = "......",
                            Name = "Danh mục tin tức 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2982),
                            Description = "......",
                            Name = "Danh mục tin tức 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2986),
                            Description = "......",
                            Name = "Danh mục tin tức 10"
                        });
                });

            modelBuilder.Entity("webtuyensinh.Models.PostModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avartar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 2,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3053),
                            Description = "......",
                            Title = "Bài viết 1"
                        },
                        new
                        {
                            Id = 2,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 2,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3058),
                            Description = "......",
                            Title = "Bài viết 2"
                        },
                        new
                        {
                            Id = 3,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 3,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3062),
                            Description = "......",
                            Title = "Bài viết 3"
                        },
                        new
                        {
                            Id = 4,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 3,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3067),
                            Description = "......",
                            Title = "Bài viết 4"
                        },
                        new
                        {
                            Id = 5,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 5,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3071),
                            Description = "......",
                            Title = "Bài viết 5"
                        },
                        new
                        {
                            Id = 6,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 5,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3076),
                            Description = "......",
                            Title = "Bài viết 6"
                        },
                        new
                        {
                            Id = 7,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 9,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3080),
                            Description = "......",
                            Title = "Bài viết 7"
                        },
                        new
                        {
                            Id = 8,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 8,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3085),
                            Description = "......",
                            Title = "Bài viết 8"
                        },
                        new
                        {
                            Id = 9,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 10,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3090),
                            Description = "......",
                            Title = "Bài viết 9"
                        },
                        new
                        {
                            Id = 10,
                            Avartar = "news-avartar.jpg",
                            CategoryId = 1,
                            Content = "<p>Đây là nội dung bài viết</p>",
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(3094),
                            Description = "......",
                            Title = "Bài viết 10"
                        });
                });

            modelBuilder.Entity("webtuyensinh.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2239),
                            Password = "123123",
                            Role = "Admin",
                            UserName = "user11"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2265),
                            Password = "123123",
                            Role = "User",
                            UserName = "user22"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 20, 19, 11, 56, 504, DateTimeKind.Local).AddTicks(2269),
                            Password = "123123",
                            Role = "User",
                            UserName = "user33"
                        });
                });

            modelBuilder.Entity("webtuyensinh.Models.PostModel", b =>
                {
                    b.HasOne("webtuyensinh.Models.CategoryModel", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("webtuyensinh.Models.CategoryModel", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
